[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "https://mediagrabber.org/:splat"
  status = 301
  force = true
  conditions = { Host = ["mediagrabber.com", "www.mediagrabber.com", "mediagrabber.netlify.app", "www.mediagrabber.netlify.app"] }

[[redirects]]
  from = "/*"
  to = "https://mediagrabber.org/:splat"
  status = 301
  force = true
  conditions = { Scheme = ["http"], Host = ["mediagrabber.org", "www.mediagrabber.org"] }

[[redirects]]
  from = "/api/meta"
  to = "/.netlify/functions/cobalt"
  status = 200

[[redirects]]
  from = "/convertisseur-video"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/unsupported-url"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/download-ai-video-mp3"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
