[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "https://mediagrabber.org/*"
  to = "https://mediagrabber.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.mediagrabber.org/*"
  to = "https://mediagrabber.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://mediagrabber.app/*"
  to = "https://mediagrabber.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mediagrabber.netlify.app/*"
  to = "https://mediagrabber.app/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/meta"
  to = "/.netlify/functions/cobalt"
  status = 200

[[redirects]]
  from = "/convertisseur-video"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/unsupported-url"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/download-ai-video-mp3"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
